/* Deterministic valuation workbench UI. Computation and validation stay server-side. */
(() => {
  'use strict';
  const METHODS = [
    ['net_income', '净利润 × P/E', '股权价值；要求规范化净利润、期间、币种/单位与可比倍数。'],
    ['ps', 'P/S（股权价值）', '收入 × P/S；净债务可用于补充企业价值桥。'],
    ['dcf', 'DCF / FCFF', '逐年 EBIT、税、D&A、CapEx、ΔNWC、WACC、终值方法与净债务。'],
    ['lbo', 'LBO / Sponsor Returns', 'Sources & uses、逐年经营现金流、债务摊还、cash sweep、退出倍数和实际日期。']
  ];
  const LABELS = {currency:'币种',unit:'金额单位',period:'期间',net_income:'净利润',pe_multiple:'P/E',diluted_shares:'稀释后股数',revenue:'收入',ps_multiple:'P/S',net_debt:'净债务',valuation_date:'估值日',wacc:'WACC',discount_timing:'折现时点',terminal_method:'终值方法',terminal_growth:'永续增长率',terminal_multiple:'终值倍数',minority_interest:'少数股东权益',entry_date:'进入日',exit_date:'退出日',entry_ev:'进入企业价值',entry_debt:'初始债务',entry_fees:'进入费用',minimum_cash:'最低现金',initial_cash:'初始现金',seller_rollover:'卖方滚存',exit_fees:'退出费用',exit_multiple:'退出倍数',tax_rate:'税率',interest_rate:'利率',mandatory_amortization:'强制偿还',cash_sweep_pct:'超额现金偿债比例',forecasts:'年度预测',year:'期间',ebit:'EBIT',ebitda:'EBITDA',ebit_margin:'EBIT率',da:'D&A',capex:'资本开支',delta_nwc:'营运资本变动'};
  const PERCENT = new Set(['wacc','terminal_growth','tax_rate','interest_rate','cash_sweep_pct','ebit_margin']);
  const PROMPTS = {
    net_income: '按净利润×P/E估值。请说明币种/单位、净利润期间、规范化净利润、P/E倍数；如需每股价值，请提供稀释后股数。未提及的值不要猜。',
    ps: '按股权P/S估值。请说明币种/单位、收入期间、收入、P/S倍数；如需EV桥，请提供净债务。未提及的值不要猜。',
    dcf: '按FCFF DCF。请提供币种/单位、估值日、折现时点、WACC、终值方法及终值假设、净债务、少数股东权益；逐年列出EBIT或收入+EBIT率、D&A、CapEx、ΔNWC和税率。未提及的值不要猜。',
    lbo: '按LBO股权回报。请提供币种/单位、进入/退出日期、进入EV/债务/交易费用/最低现金/初始现金/卖方滚存、退出费用/退出倍数；逐年列出EBITDA、D&A、CapEx、ΔNWC、税率、利率、强制摊还及cash sweep比例。未提及的交易条款不要猜。'
  };
  function render({state, boot, helpers:h}) {
    const method = state.valuationMethod || 'net_income';
    const methodOptions = METHODS.map(item => '<option value="' + h.esc(item[0]) + '"' + (item[0] === method ? ' selected' : '') + '>' + h.esc(item[1]) + '</option>').join('');
    const modelOptions = h.dshModelOptions(state.valuationModel || 'gpt-6-luna');
    const proposal = state.valuationProposal;
    const assumptions = proposal && proposal.assumptions && typeof proposal.assumptions === 'object' ? proposal.assumptions : null;
    const missing = proposal && Array.isArray(proposal.missing) ? proposal.missing : [];
    const unknown = proposal && Array.isArray(proposal.unmapped_fields) ? proposal.unmapped_fields : [];
    const scalarRows = assumptions ? Object.entries(assumptions).filter(([,value]) => value === null || typeof value !== 'object').map(([key,value]) => '<div class="finance-stat"><span>' + h.esc(LABELS[key] || key) + '</span><b>' + h.esc(PERCENT.has(key) && Number.isFinite(Number(value)) ? h.percent(value) : (typeof value === 'number' ? h.number(value) : String(value ?? '待补充'))) + '</b></div>').join('') : '';
    const forecastRows = assumptions && Array.isArray(assumptions.forecasts) ? '<div class="table-scroll mt-12"><table><thead><tr><th>期间</th><th>EBITDA / EBIT</th><th>D&A</th><th>CapEx</th><th>ΔNWC</th></tr></thead><tbody>' + assumptions.forecasts.map(row => '<tr><td>' + h.esc(row.year ?? '待补充') + '</td><td>' + h.esc(row.ebitda != null ? h.number(row.ebitda) : (row.ebit != null ? h.number(row.ebit) : '待补充')) + '</td><td>' + h.esc(row.da ?? '待补充') + '</td><td>' + h.esc(row.capex ?? '待补充') + '</td><td>' + h.esc(row.delta_nwc ?? '待补充') + '</td></tr>').join('') + '</tbody></table></div>' : '';
    const review = proposal ? '<section class="panel mt-18 valuation-review"><div class="row between"><h3>AI提取的假设（计算前请核对）</h3><span class="badge green">待人工确认</span></div><p class="tiny muted">计算由本地确定性公式完成；模型只提取自然语言，不代算、不补缺失值。</p>' + (scalarRows ? '<div class="finance-stats">' + scalarRows + '</div>' : '') + forecastRows + (missing.length ? '<div class="mt-12">' + h.banner('还缺少假设', missing.map(key => LABELS[key] || key).join('、'), 'amber', 'warning') + '</div>' : '') + (unknown.length ? '<div class="mt-12">' + h.banner('有未映射字段', unknown.join('、'), 'amber', 'warning') + '</div>' : '') + (proposal.clarifications && proposal.clarifications.length ? '<ul class="mt-12">' + proposal.clarifications.map(q => '<li>' + h.esc(q) + '</li>').join('') + '</ul>' : '') + '<details class="mt-18"><summary>高级：查看/编辑结构化假设 JSON</summary><textarea id="valuation-json" class="editor-body" rows="14" spellcheck="false">' + h.esc(state.valuationJson || JSON.stringify(assumptions || {}, null, 2)) + '</textarea></details><div class="row mt-18"><button type="button" class="button primary" data-action="valuation-calculate" ' + (state.valuationPending ? 'disabled' : '') + '>' + (state.valuationPending ? '正在计算…' : '确认这组假设并计算') + '</button></div></section>' : '';
    const result = state.valuationResult ? renderResult(state.valuationResult, h) : '';
    const dshBanner = boot && boot.dsh && boot.dsh.available ? h.banner('GPT / DSH 已连接', '仅将上方自然语言假设发送到本机 DSH；不自动发送项目资料或记忆。每次解析需单次授权。计算在本地代码中完成。', 'blue', 'external') : h.banner('未检测到 DSH', '仍可选择估值方法并编辑结构化假设；自然语言解析需先连接 DSH。', 'amber', 'warning');
    const actions = '';
    return h.heading('估值与回报模型', 'FUNDAMENTALS FIRST', '选方法 → 用自然语言描述主要假设 → 核对结构化输入 → 本地公式计算。缺失的关键口径不会被自动填成零。', actions) +
      '<div class="stack"><section class="panel question-panel"><div class="row wrap between"><div class="field"><label for="valuation-method">估值方法</label><select id="valuation-method">' + methodOptions + '</select></div><div class="field"><label for="valuation-project">关联项目</label><select id="valuation-project">' + h.projectOptions(state.valuationProjectId || '') + '</select></div>' +
      (boot?.dsh?.available ? '<div class="field"><label for="valuation-model">假设解析模型</label><select id="valuation-model">' + modelOptions + '</select></div>' : '') + '</div><p class="mt-12">' + h.esc(METHODS.find(x => x[0] === method)?.[2] || '') + '</p><label for="valuation-text">自然语言假设</label><textarea id="valuation-text" rows="6" maxlength="12000" placeholder="' + h.esc(PROMPTS[method]) + '">' + h.esc(state.valuationText || '') + '</textarea><div class="mt-12">' + dshBanner + '</div><p class="inline-note">点“用 GPT/DSH 整理假设”即直接发送上方这段描述；不发送项目资料，也不发送个人记忆。</p><div class="row wrap mt-12"><button type="button" class="button small soft" data-action="valuation-template">填入本方法假设提纲</button><button type="button" class="button primary" data-action="valuation-parse" ' + (state.valuationPending || !boot?.dsh?.available ? 'disabled' : '') + '>' + (state.valuationPending ? '正在解析…' : '用 GPT/DSH 整理假设') + '</button></div>' + (state.valuationError ? '<div class="mt-12">' + h.banner('处理未完成', state.valuationError, 'error', 'warning') + '</div>' : '') + '</section>' + review + result + '</div>';
  }
  function renderResult(result, h) {
    const method = result.method;
    const metrics = method === 'lbo' ? [['股权IRR', h.percent(result.irr)], ['MOIC', h.number(result.moic) + '×'], ['初始股权投入', h.number(result.entry_sponsor_equity) + ' ' + result.unit], ['退出回收', h.number(result.sponsor_proceeds) + ' ' + result.unit]] : method === 'dcf' ? [['企业价值', h.number(result.enterprise_value) + ' ' + result.unit], ['股权价值', h.number(result.equity_value) + ' ' + result.unit], ['终值现值占比', result.terminal_value_share == null ? '—' : h.percent(result.terminal_value_share)], ['WACC', h.percent(result.wacc)]] : [['股权价值', h.number(result.equity_value) + ' ' + result.unit], ['每股价值', result.implied_value_per_share == null ? '—' : h.number(result.implied_value_per_share)], [method === 'net_income' ? 'P/E' : 'P/S', h.number(method === 'net_income' ? result.pe_multiple : result.ps_multiple) + '×'], ['期间', h.esc(result.period || '—')]];
    let body = '<section class="panel valuation-result"><div class="row between"><h2>' + h.esc(result.method_label || '估值结果') + '</h2><span class="badge green">本地计算</span></div><div class="finance-stats">' + metrics.map(x => '<div><span>' + h.esc(x[0]) + '</span><b>' + h.esc(x[1]) + '</b></div>').join('') + '</div>';
    const yearlyRows = result.forecast || result.rows; if (Array.isArray(yearlyRows)) body += '<div class="table-scroll mt-18"><table><thead><tr><th>期间</th><th>EBIT / EBITDA</th><th>税</th><th>CapEx</th><th>ΔNWC</th><th>FCFF / 期末债务</th></tr></thead><tbody>' + yearlyRows.map(row => '<tr><td>' + h.esc(row.year) + '</td><td>' + h.number(row.ebit ?? row.ebitda) + '</td><td>' + h.number(row.tax ?? 0) + '</td><td>' + h.number(row.capex ?? 0) + '</td><td>' + h.number(row.delta_nwc ?? 0) + '</td><td>' + h.number(row.fcff ?? row.ending_debt) + '</td></tr>').join('') + '</tbody></table></div>';
    if (result.sensitivity) body += '<div class="table-scroll mt-18"><table class="sensitivity-table"><thead><tr><th>' + h.esc(result.sensitivity.row_label) + ' / ' + h.esc(result.sensitivity.column_label) + '</th>' + result.sensitivity.columns.map(v => '<th>' + h.esc(result.sensitivity.column_label === 'Exit Multiple' ? h.number(v) + '×' : h.percent(v)) + '</th>').join('') + '</tr></thead><tbody>' + result.sensitivity.rows.map((v,i) => '<tr><th>' + h.esc(h.percent(v)) + '</th>' + (result.sensitivity.values[i] || []).map(x => '<td>' + h.esc(x == null ? '—' : result.method === 'lbo' ? h.percent(x) : h.number(x)) + '</td>').join('') + '</tr>').join('') + '</tbody></table></div>';
    body += '<div class="mt-18">' + h.banner('公式与限制', result.formula + (result.warning ? ' ' + result.warning : ''), 'amber', 'info') + '</div><div class="row mt-18"><button type="button" class="button soft" data-action="valuation-save">保存为项目模型记录</button></div></section>';
    return body;
  }
  window.LocalWorkOSValuation = {render, templates:PROMPTS};
})();
